[providers.age]
type = "age"
recipients = [
  "age1q8f03l7hmyrk3wazqddc40ucc7rtvugl527pp9lxahvl8rar5p2q2plg56", # macbook-pro
]

[secrets]
# Shared postgres password (used by all apps)
POSTGRES_PASSWORD = { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNMjJSMkhFMzlsV2FQak9QZ3JVTDl4ei8xQlRvTUxkVjdzbHU0cU9RaUdnCnlnSkllRU56ZFRhRy9qa2JYdlo1Qm9mbXNmeW1LQkdtdG1ld2dheXNvZ00KLS0tIDJjSXBEemFMaktVWS9yQ3B5K2ZrVzVPS01RTUZ3S201WXhUU1JqRS9VQ0kKv8toDZcgaTuLGu6hP1KE3Hd/1GR2aSh9jTZWofAhCwGTMUuYeXTk/3C474Xccsgiapr2LKSOROFGIGYXc2b7NxBJHWMMwKQYNtBTvQ==" }

# Onyx secrets
ONYX_SECRET = { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBleGY5UHhCVHA4L2JGVEo0TWNyNGgzbGhFcmVBT1FiWFgrMjFnQzBDY0M4Ck9KVVNRdktSS1dGb3ZqMThLdEJBNzcwME42QkFNM29uS1M0SkRjdEUvRHcKLS0tIE52NDFxT3VjN1ptb2hHQzdKU1FXME9uUXB5a3NYK1dTbWFlZ0JVY2hRY0kK5Y/GuA+cw63sPjv4UANquEHH76wJ1ygfqHlu3D1uf3ZTNjEdPcB2prGT4n8ZdWBl3UULLY94voU/fQ2ANjJeCM2ugAm7/1EFAy6DgQ==" }
ONYX_MINIO_ROOT_PASSWORD = { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1N1Q5dE9HZEhPTlZhSExwMDFWajJweGhrQnN2QWdZL0YxM0kzR1lCMnpvCk1ld3dJaFFwaTc0aEJxaFd3MDd1bFhJbVVyZHpabkRDTTAzWnRuVjlDdmsKLS0tIEdiTThTdkZYVGdzdHhNV1pPWkdxRmtESzNiaUE5c3dTUXNmNW1MWCt6TlkKhmcD/sgeenMcOnbx/Se4loi9l5E8cyrti6no6toB5XwqpRpSMlJSXYfx8lnCPY3yzYchhcgvlBvdAmM0zO6xxA==" }
