package goutils

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"log/slog"
	"regexp"
)

// ShouldRefactor checks if a Go file contains only function, type, and import declarations,
// does not contain an init function, and isn't excluded by special comments.
func ShouldRefactor(filePath string) (should bool, exclusionReason string, err error) {
	fset := token.NewFileSet()
	node, err := parser.ParseFile(fset, filePath, nil, parser.ParseComments)
	if err != nil {
		return false, "error parsing file", err
	}

	// Check for special comments in all comment groups
	dissectIgnoreFileComment := regexp.MustCompile(`^//\s*dissect:ignoreFile([^\w]|$)`)
	sqlcAutoGeneratedComment := regexp.MustCompile(`^// Code generated by sqlc. DO NOT EDIT\.$`)
	slog.Debug("Node comments", "comments", node.Comments)
	for _, commentGroup := range node.Comments {
		for _, comment := range commentGroup.List {
			slog.Debug("Checking comment", "text", comment.Text)
			if dissectIgnoreFileComment.MatchString(comment.Text) {
				return false, "`// dissect:ignoreFile` comment", nil
			}
			if sqlcAutoGeneratedComment.MatchString(comment.Text) {
				return false, "`// Code generated by sqlc` comment", nil
			}
			slog.Debug("No special comment found", "text", comment.Text)
		}
	}

	for _, decl := range node.Decls {
		switch d := decl.(type) {
		case *ast.FuncDecl:
			// Function declarations are allowed, but init functions are not since they are supposed to apply to the whole file?
			// TODO: research whether we can lift this restriction. I'm not even sure it's true.
			if d.Name.Name == "init" {
				return false, "file contains an `init` function", nil
			}
			continue
		case *ast.GenDecl:
			// General declarations (imports, types, consts, vars)
			if d.Tok == token.IMPORT {
				continue
			}
			if d.Tok == token.TYPE {
				if IsTestFile(filePath) {
					// TODO: why exactly do we restrict this?
					return false, "test file contains a type declaration", nil
				}
				continue
			}
			// Other general declarations (consts, vars) are not allowed
			return false, fmt.Sprintf("file contains a %s", d.Tok.String()), nil
		default:
			// Any other declaration type is not allowed
			return false, fmt.Sprintf("file contains a %s", fmt.Sprintf("%T", decl)), nil
		}
	}
	return true, "", nil
}
