[[project]]
dir = "claude-trace"
module = "claude-trace"

[[project]]
dir = "conf"
module = "conf"

[[project]]
dir = "dissect"
module = "dissect"

[[project]]
dir = "ingest"
module = "ingest"

[[project]]
dir = "lib/cli"
module = "github.com/neongreen/mono/lib/cli"

[[project]]
dir = "lib/configschema"
module = "github.com/neongreen/mono/lib/configschema"

[[project]]
dir = "lib/ghclient"
module = "github.com/neongreen/mono/lib/ghclient"

[[project]]
dir = "lib/ghrelease"
module = "github.com/neongreen/mono/lib/ghrelease"

[[project]]
dir = "lib/toml"
module = "github.com/neongreen/mono/lib/toml"

[[project]]
dir = "lib/version"
module = "github.com/neongreen/mono/lib/version"

[[project]]
dir = "markdown-format"
module = "github.com/neongreen/mono/markdown-format"

[[project]]
dir = "printpdf"
module = "github.com/neongreen/mono/printpdf"

[[project]]
dir = "prrun"
module = "github.com/neongreen/mono/prrun"

[[project]]
dir = "tk"
module = "github.com/neongreen/mono/tk"

[[project]]
dir = "want"
module = "github.com/neongreen/mono/want"
