[tasks.run]
description = "Build and run"
run = "go run ."

[tasks.fmt]
description = "Format Go code"
run = "go fmt ./..."

[tasks.check]
description = "Check that Go code and tests compile and type check"
run = "go test -run=^$ ./..."
