apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin-gvisor
  namespace: sample-apps
  labels:
    app: httpbin-gvisor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin-gvisor
  template:
    metadata:
      labels:
        app: httpbin-gvisor
    spec:
      runtimeClassName: gvisor
      containers:
        - name: httpbin
          image: kennethreitz/httpbin
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin-gvisor
  namespace: sample-apps
spec:
  selector:
    app: httpbin-gvisor
  ports:
    - port: 80
      targetPort: 80
