package main

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/klauspost/compress/zstd"
	"github.com/neongreen/mono/tk/internal/sync"
)

// TestCollisionDetection_LocalNodeInRemote tests that collision detection
// works when the remote contains events generated by the local machine.
// This is a regression test for the issue where CheckSegment filters out
// events matching the local node ID, preventing CheckForCollisions from
// ever detecting a collision.
func TestCollisionDetection_LocalNodeInRemote(t *testing.T) {
	// Setup: Create a temporary directory for test segments
	tempDir := t.TempDir()
	segmentDir := filepath.Join(tempDir, "segments")
	if err := os.MkdirAll(segmentDir, 0755); err != nil {
		t.Fatalf("failed to create segment dir: %v", err)
	}

	localNodeID := "node-abc123"

	// Create a segment file containing events from the local node
	// This simulates the scenario where the remote contains events
	// that were generated by this machine
	segmentPath := filepath.Join(segmentDir, "test_segment.jsonl.zst")
	events := []sync.SegmentEvent{
		{
			Schema:  "v1",
			ID:      "event1",
			Lamport: 1,
			TS:      time.Now().Format(time.RFC3339),
			Node:    localNodeID, // types.Event from local node
			Space:   "personal",
			Actor:   "test-user",
			Role:    "human",
			Kind:    "task.created",
			Payload: map[string]interface{}{"title": "Test task"},
		},
		{
			Schema:  "v1",
			ID:      "event2",
			Lamport: 2,
			TS:      time.Now().Format(time.RFC3339),
			Node:    "node-xyz789", // types.Event from different node
			Space:   "personal",
			Actor:   "test-user",
			Role:    "human",
			Kind:    "task.created",
			Payload: map[string]interface{}{"title": "Another task"},
		},
	}

	// Write the segment file
	if err := writeSegmentFile(segmentPath, events); err != nil {
		t.Fatalf("failed to write segment file: %v", err)
	}

	// Test: Create a collision checker and check the segment
	checker := NewNodeCollisionChecker(localNodeID)
	if err := checker.CheckSegment(segmentPath); err != nil {
		t.Fatalf("CheckSegment failed: %v", err)
	}

	// Verify: The collision checker should detect that the local node ID
	// appears in the remote events
	err := checker.CheckForCollisions()
	if err == nil {
		t.Errorf("Expected collision detection to return an error when local node ID appears in remote, but got nil")
		t.Logf("seenNodes map contains: %v", checker.seenNodes)
		t.Logf("localNodeID: %s", checker.localNodeID)
		t.Logf("This confirms the bug: CheckSegment filters out the local node ID (line 32-34),")
		t.Logf("so seenNodes never contains it, and CheckForCollisions can't detect the collision.")
	} else {
		t.Logf("Successfully detected collision: %v", err)
	}

	// Also check that non-local nodes were recorded
	seenNodes := checker.GetSeenNodes()
	foundOtherNode := false
	for _, node := range seenNodes {
		if node == "node-xyz789" {
			foundOtherNode = true
			break
		}
	}
	if !foundOtherNode {
		t.Errorf("Expected to see node-xyz789 in seenNodes, but it was not found")
	}
}

// TestCollisionDetection_OnlyRemoteNodes tests that when a remote contains
// only events from other nodes (not the local node), no collision is detected.
func TestCollisionDetection_OnlyRemoteNodes(t *testing.T) {
	tempDir := t.TempDir()
	segmentDir := filepath.Join(tempDir, "segments")
	if err := os.MkdirAll(segmentDir, 0755); err != nil {
		t.Fatalf("failed to create segment dir: %v", err)
	}

	localNodeID := "node-local"

	// Create a segment with only remote node events
	segmentPath := filepath.Join(segmentDir, "test_segment.jsonl.zst")
	events := []sync.SegmentEvent{
		{
			Schema:  "v1",
			ID:      "event1",
			Lamport: 1,
			TS:      time.Now().Format(time.RFC3339),
			Node:    "node-remote1",
			Space:   "personal",
			Actor:   "test-user",
			Role:    "human",
			Kind:    "task.created",
			Payload: map[string]interface{}{"title": "Test task"},
		},
		{
			Schema:  "v1",
			ID:      "event2",
			Lamport: 2,
			TS:      time.Now().Format(time.RFC3339),
			Node:    "node-remote2",
			Space:   "personal",
			Actor:   "test-user",
			Role:    "human",
			Kind:    "task.created",
			Payload: map[string]interface{}{"title": "Another task"},
		},
	}

	if err := writeSegmentFile(segmentPath, events); err != nil {
		t.Fatalf("failed to write segment file: %v", err)
	}

	checker := NewNodeCollisionChecker(localNodeID)
	if err := checker.CheckSegment(segmentPath); err != nil {
		t.Fatalf("CheckSegment failed: %v", err)
	}

	// Should not detect a collision since local node is not in remote
	err := checker.CheckForCollisions()
	if err != nil {
		t.Errorf("Expected no collision, but got error: %v", err)
	}

	// Verify that remote nodes were recorded
	seenNodes := checker.GetSeenNodes()
	if len(seenNodes) != 2 {
		t.Errorf("Expected 2 seen nodes, got %d: %v", len(seenNodes), seenNodes)
	}
}

// writeSegmentFile is a helper to write events to a compressed segment file
func writeSegmentFile(path string, events []sync.SegmentEvent) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	encoder, err := zstd.NewWriter(f)
	if err != nil {
		return err
	}
	defer encoder.Close()

	for _, event := range events {
		eventJSON, err := json.Marshal(event)
		if err != nil {
			return err
		}
		if _, err := encoder.Write(eventJSON); err != nil {
			return err
		}
		if _, err := encoder.Write([]byte("\n")); err != nil {
			return err
		}
	}

	return nil
}
