apiVersion: v1
kind: Secret
metadata:
  name: backstage-postgres
  namespace: backstage
type: Opaque
stringData:
  postgres-password: "${BACKSTAGE_DB_PASSWORD}"
  password: "${BACKSTAGE_DB_PASSWORD}"
  postgres-user: "postgres"
  username: "backstage"
