name: diagram-dsl

on:
  push:
    paths:
      - "diagram-dsl/**"
      - ".github/workflows/diagram-dsl.yml"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: "20"

      - name: Install dependencies
        working-directory: diagram-dsl
        run: npm ci

      - name: Run linter
        working-directory: diagram-dsl
        run: npm run lint

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: "20"

      - name: Install dependencies
        working-directory: diagram-dsl
        run: npm ci

      - name: Run tests
        working-directory: diagram-dsl
        run: npm run test:lint

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: "20"

      - name: Install dependencies
        working-directory: diagram-dsl
        run: npm ci

      - name: Build
        working-directory: diagram-dsl
        run: npm run build
